#!/bin/bash

# Prints a notice if composer files are changed.
# https://github.com/greg0ire/git_template/blob/master/hooks/php/composer/post-checkout

if [ "$1" == "0000000000000000000000000000000000000000" ]; then
    echo -e "\e[92mThat was a git clone? No check for file mods.\e[0m"
    exit 0;
fi

MODIFIED_FILES=`git diff --name-only $1..$2`                                                                                                             

 while read -r LINE; do
    if [[ $LINE =~ ^composer.lock$ ]]; then
        echo -e "\e[37;41mNOTICE: composer.lock is modified. Run: composer install\e[0m"
    elif [[ $LINE =~ ^composer.json$ ]]; then   
        echo -e "\e[37;41mNOTICE: composer.json is modified. Run: composer dump-autoload\e[0m"
    fi
 done <<< "$MODIFIED_FILES"
