#!/bin/bash

# Prints a notice if composer files are changed.
# https://gist.github.com/sindresorhus/7996717
# https://github.com/greg0ire/git_template/blob/master/hooks/php/composer/post-merge

MODIFIED_FILES=`git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD`

while read -r LINE; do
    if [[ $LINE =~ ^composer.lock$ ]]; then
        echo -e "\e[37;41mNOTICE: composer.lock is modified. Run: composer install\e[0m"
    elif [[ $LINE =~ ^composer.json$ ]]; then
        echo -e "\e[37;41mNOTICE: composer.json is modified. Run: composer dump-autoload\e[0m"
    fi
done <<< "$MODIFIED_FILES"
